"""Initial migration

Revision ID: 3b95eef01c11
Revises: 
Create Date: 2024-07-06 18:38:05.334748

"""
from typing import Sequence, Union

import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa

from database import models

# revision identifiers, used by Alembic.
revision: str = '3b95eef01c11'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sqlalchemy_utils.types.choice.ChoiceType(models.Node.TYPES), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('yesNode_id', sa.Integer(), nullable=True),
    sa.Column('noNode_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['noNode_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['original_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['yesNode_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Workflow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_node_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['start_node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Workflow')
    op.drop_table('nodes')
    # ### end Alembic commands ###
